apiVersion: skaffold/v4beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: bkoprucu/distributedcounter
      jib:
        args:
          - -Dmaven.test.skip=true

manifests:
  rawYaml:
    - k8s/rbac.yml
    - k8s/configmap.yml
    - k8s/deployment.yml

profiles:
  - name: dockerfile
    build:
      artifacts:
        - image: bkoprucu/distributedcounter
          docker:
            dockerfile: Dockerfile
