server:
  port: 8080
  shutdown: graceful
  compression.enabled: false

spring:
  application.name: distributed-counter
  lifecycle:
    timeout-per-shutdown-phase: 5
  main:
    lazy-initialization: true
    web-application-type: REACTIVE
    banner-mode: off

management:
  endpoints:
    web.exposure.include: "*"  # Unsafe - not for production
    enabled-by-default: true
  endpoint:
    env:
      keys-to-sanitize: "password,secret"
      show-values: ALWAYS   # Unsafe - not for production
    configprops:
      show-values: ALWAYS   # Unsafe - not for production

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging.level:
  org.berk: DEBUG

hazelcastcounter:
  cluster-name: "counter-cluster"
  kubernetes-service-name: "distributed-counter" # Should match the service in deployment.yml
  implementation-class-name: "HazelcastPNCounter" # or "HazelcastEntryProcessorCounter"