management:
  endpoints:
    web.exposure.include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging.level:
  org.berk: DEBUG

hazelcastcounter:
  cluster-name: "counter-cluster"
