management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
  info.build.enabled: true

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging.level:
  org.berk: DEBUG

hazelcastcounter:
  cluster-name: "counter-cluster"
