management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
  endpoint:
    env:
      keys-to-sanitize: "password,secret"
      show-values: ALWAYS

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging.level:
  org.berk: DEBUG

hazelcastcounter:
  cluster-name: "counter-cluster"
  kubernetes-service-name: "distributedcounter-hazelcast-service" # Should match the service in deployment.yml