kind: ConfigMap
apiVersion: v1
metadata:
  name: distributed-counter # Should match spring.application.name for spring-cloud-kubernetes to pick it up
  labels:
    app: distributed-counter

data:
  hazelcastcounter.cluster-name: "counter-cluster-kubernetes"
  hazelcastcounter.instance-name: "counter-instance-kubernetes"
