apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributedcounter-deployment
  labels:
    app: distributedcounter-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: distributedcounter-app
  template:
    metadata:
      labels:
        app: distributedcounter-app
    spec:
      containers:
        - name: distributedcounter
          image: bkoprucu/distributedcounter
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: service-port
            - containerPort: 5701
              name: hazelcast-port
          env:
            - name: spring_profiles_active
              value: kubernetes
            - name: JAVA_OPTS
              value: "-Xss1024k -XX:MaxRAMPercentage=75"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe: # will restart if fails
            httpGet:
              port: service-port
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: service-port
              path: /actuator/health/readiness
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 1
          resources:
            requests:
              memory: 512M
            limits:
              memory: 1024M
---

apiVersion: v1
kind: Service
metadata:
  name: distributedcounter-service
  labels:
    app: distributedcounter-app
spec:
  type: LoadBalancer
  selector:
    app: distributedcounter-app
  ports:
    # Enable below port and disable ClusterIP service to access Hazelcast from the outside
    #- port: 5701
    #  name: hazelcast
    - port: 8080
      name: service
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: distributedcounter-hazelcast-service # Should match with the value set in HazelcastConfigBuilder.withKubernetesDiscovery()
  labels:
    app: distributedcounter-app
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: distributedcounter-app
  ports:
    - port: 5701
      name: hazelcast
