apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: distributedcounter
  name: distributedcounter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distributedcounter
  template:
    metadata:
      labels:
        app: distributedcounter
    spec:
      containers:
        - image: bkoprucu/distributedcounter:0.1.1
          imagePullPolicy: IfNotPresent
          name: distributedcounter
          ports:
            - containerPort: 8080
            - containerPort: 5701
          env:
            - name: enableKubernetes

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: distributedcounter
  name: distributedcounter
spec:
  type: LoadBalancer
  selector:
    app: distributedcounter
  ports:
    - port: 5701
      name: hazelcast
    - port: 8080
      name: http
      targetPort: 8080
