apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-counter
  labels:
    app: distributed-counter

spec:
  replicas: 2
  selector:
    matchLabels:
      app: distributed-counter
  strategy: {}
  template:
    metadata:
      labels:
        app: distributed-counter
    spec:
      containers:
        - name: distributedcounter
          image: localhost:6000/bkoprucu/distributedcounter
        # imagePullPolicy: Always  # 'Always' not compatible with Skaffold
          ports:
            - containerPort: 8080
              name: service-port
            - containerPort: 5701
              name: hazelcast-port
          envFrom:
            - configMapRef:
                name: distributed-counter
          env:
            - name: spring_profiles_active
              value: kubernetes
            - name: JAVA_OPTS
              value: "-Xss1024k -XX:MaxRAMPercentage=75"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe: # will restart if fails
            httpGet:
              port: service-port
              path: /actuator/health/liveness
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: service-port
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
              memory: 512M
            limits:
              memory: 1024M
status: {}
