server:
  port: 8080
  shutdown: GRACEFUL

management:
  endpoints:
    web.exposure.include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

counter:
  group-name: counter_group_default
  use-local-caching: true           # If true, use PeriodicDistributingCounter, otherwise use HazelcastCounter
  local-cache-sync-interval: 500ms  # Sync interval for PeriodicDistributingCounter
