server:
  port: 8080
  shutdown: GRACEFUL

spring:
  main:
    lazy-initialization: true
    cloud-platform: KUBERNETES

management:
  endpoint.health.show-details: ALWAYS
  endpoints:
    web.exposure.include: "*"

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true


counter:
  PeriodicDistributingCounter:
    enabled: true # Set false to use HazelcastCounter
    syncInterval: 500   # Delay between sync operations in PeriodicDistributingCounter
